### ISSUE TITLE
I need some help please

### ISSUE THREAD

**Issue by beginner984** [drisso/RUVSeq#12]
Sorry
Having control and treatment, what is the application of `W_1` in this formula

```
dds <- DESeqDataSetFromMatrix(countData = counts(set1),
#                                colData = pData(set1),
#                                design = ~ W_1 + x)
```
I think x is the main design but I can not understand the role of `W_1` here

What if I eliminate that?

My impression says that we already imply unwanted variation sources by this

`set1 <- RUVg(set, spikes, k=1) `

So having set1 in the formula should work but why we need `W_1` too?

In addition to treatment versus control which if my phenotype of intrest, I also have several batches for data collection

So, I am not sure how to place my batches and the comparing my phenotypes

Thanks for any help

**Comment by drisso** [comment]
Hi @beginner984 ,

this is really more of a question for the Bioconductor support forum (https://support.bioconductor.org/). 

I would encourage you to search in the forum to see if a similar question was already answered, and if not, to pose your question there. This way, you will have a larger set of people able to help you and the answer will be of help to people that might have similar questions in the future. This is particularly true in this case, as you have a question about two different packages (DESeq2 and RUVSeq -- you are asking here but the function you are using is from DESeq2).

GIthub issues are more appropriate for questions about the code/implementation or to report bugs. It's helpful to think of it as users' (support forum) vs. developers' (github) issues/questions.

In this case, I think that you are misunderstanding the meaning of colData and design in the `DESeqDataSetFromMatrix` function: colData just tells the function *where* to find the variables used in the formula, while design tells it the actual formula to use. Hence, it is irrelevant that `set1` already has the factors of unwanted variation, it is by including them in the design formula that you instruct the model to account for them.

I hope this helps.

**Comment by beginner984** [comment]
Thanks a lot

Please ,if you just tell me in your code what `W_1` is?

I know `x` is the main design (three controls versus three treatments); But I am sure `W_1` comes from where?

Is that correcting factor based on spikes in gene?

For instance as a part of your tutorial you mention

**_This is done by considering a design matrix that includes both the covariates of interest
(here, the treatment status) and the factors of unwanted variation._**
`design <- model.matrix(~x + W_1, data=pData(set1))`

I have both covariate of interest and some some batches, so shall I still include the batch in the formula? 

Thanks for any clarification

**Comment by RamRS** [comment]
@beginner984, you have already frustrated plenty of users at bioconductor support, biostars and bioinformatics SE with your low effort questions over several years - don't do this using GitHub issues - they're not supposed to be support threads. Invest more effort and stick to support forums.
