### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by lizhaozhi** [drisso/RUVSeq#4]
Hi,

I tried to install RUVSeq on my MacBook. it is not working. appreciate your idea. 

=====

BiocManager::install("RUVSeq")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.2 (2020-06-22)
Installing package(s) 'RUVSeq'
trying URL 'https://bioconductor.org/packages/3.11/bioc/bin/macosx/contrib/4.0/RUVSeq_1.22.0.tgz'
Content type 'application/x-gzip' length 186310 bytes (181 KB)
==================================================
downloaded 181 KB

The downloaded binary packages are in
	/var/folders/_3/_hmmdm0d3b94hb2s2r7t37c00000gn/T//RtmpSCyQ1m/downloaded_packages
Old packages: 'deldir', 'Rfast'
Update all/some/none? [a/s/n]: 
a

  There are binary versions available but the source versions are later:
       binary source needs_compilation
deldir 0.1-28 0.1-29              TRUE
Rfast   2.0.0  2.0.1              TRUE

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) Yes
installing the source packages ‘deldir’, ‘Rfast’

trying URL 'https://cran.rstudio.com/src/contrib/deldir_0.1-29.tar.gz'
Content type 'application/x-gzip' length 108416 bytes (105 KB)
==================================================
downloaded 105 KB

trying URL 'https://cran.rstudio.com/src/contrib/Rfast_2.0.1.tar.gz'
Content type 'application/x-gzip' length 313781 bytes (306 KB)
==================================================
downloaded 306 KB

* installing *source* package ‘deldir’ ...
** package ‘deldir’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c acchk.f -o acchk.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c addpt.f -o addpt.o
addpt.f:28:5:

   28 | 23004 continue
      |     1
Warning: Label 23004 at (1) defined but not used [-Wunused-label]
addpt.f:27:5:

   27 | 23003 if(.not.(ngap.eq.n))goto 23002
      |     1
Warning: Label 23003 at (1) defined but not used [-Wunused-label]
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c adjchk.f -o adjchk.o
adjchk.f:29:5:

   29 | 23009 continue
      |     1
Warning: Label 23009 at (1) defined but not used [-Wunused-label]
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c binsrt.f -o binsrt.o
binsrt.f:70:5:

   70 | 23019 continue
      |     1
Warning: Label 23019 at (1) defined but not used [-Wunused-label]
binsrt.f:51:5:

   51 | 23005 continue
      |     1
Warning: Label 23005 at (1) defined but not used [-Wunused-label]
binsrt.f:61:5:

   61 | 23003 continue
      |     1
Warning: Label 23003 at (1) defined but not used [-Wunused-label]
binsrt.f:26:5:

   26 | 23001 continue
      |     1
Warning: Label 23001 at (1) defined but not used [-Wunused-label]
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c circen.f -o circen.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c cross.f -o cross.o
cross.f:23:5:

   23 | 23003 continue
      |     1
Warning: Label 23003 at (1) defined but not used [-Wunused-label]
cross.f:77:0:

   77 |       cprd = (a*d - b*c)/smin
      | 
Warning: 'smin' may be used uninitialized in this function [-Wmaybe-uninitialized]
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c crossutil.f -o crossutil.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c delet.f -o delet.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c delet1.f -o delet1.o
delet1.f:11:5:

   11 | 23005 continue
      |     1
Warning: Label 23005 at (1) defined but not used [-Wunused-label]
delet1.f:17:5:

   17 | 23001 continue
      |     1
Warning: Label 23001 at (1) defined but not used [-Wunused-label]
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c delout.f -o delout.o
delout.f:41:5:

   41 | 23009 continue
      |     1
Warning: Label 23009 at (1) defined but not used [-Wunused-label]
delout.f:21:5:

   21 | 23003 continue
      |     1
Warning: Label 23003 at (1) defined but not used [-Wunused-label]
delout.f:47:5:

   47 | 23001 continue
      |     1
Warning: Label 23001 at (1) defined but not used [-Wunused-label]
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c delseg.f -o delseg.o
delseg.f:29:5:

   29 | 23003 continue
      |     1
Warning: Label 23003 at (1) defined but not used [-Wunused-label]
delseg.f:31:5:

   31 | 23001 continue
      |     1
Warning: Label 23001 at (1) defined but not used [-Wunused-label]
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c dirout.f -o dirout.o
dirout.f:80:5:

   80 | 23003 continue
      |     1
Warning: Label 23003 at (1) defined but not used [-Wunused-label]
dirout.f:85:5:

   85 | 23001 continue
      |     1
Warning: Label 23001 at (1) defined but not used [-Wunused-label]
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c dirseg.f -o dirseg.o
dirseg.f:137:5:

  137 | 23007 continue
      |     1
Warning: Label 23007 at (1) defined but not used [-Wunused-label]
dirseg.f:139:5:

  139 | 23005 continue
      |     1
Warning: Label 23005 at (1) defined but not used [-Wunused-label]
dirseg.f:37:5:

   37 | 23001 continue
      |     1
Warning: Label 23001 at (1) defined but not used [-Wunused-label]
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c dldins.f -o dldins.o
/usr/bin/gcc64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/opt/gettext/include -I/usr/local/opt/llvm/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include   -fPIC  -g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe -c init.c -o init.o
/bin/sh: /usr/bin/gcc64: No such file or directory
make: *** [init.o] Error 127
ERROR: compilation failed for package ‘deldir’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/deldir’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/deldir’
* installing *source* package ‘Rfast’ ...
** package ‘Rfast’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/llvm/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include   -fPIC  -Wall -g -O2  -c Diag.cpp -o Diag.o
In file included from Diag.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadilloForward.h:26:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:314:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:315:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:316:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/usr/local/include/math.h:749:12: note: 'finite' declared here
extern int finite(double)
           ^
In file included from Diag.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadilloForward.h:26:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isgreater' in the global namespace
using ::isgreater;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isgreaterequal' in the global namespace
using ::isgreaterequal;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:323:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:324:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:332:9: error: no member named 'abs' in the global namespace; did you mean 'fabs'?
using ::abs;
      ~~^
/usr/local/include/math.h:417:15: note: 'fabs' declared here
extern double fabs(double);
              ^
In file included from Diag.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadilloForward.h:26:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:552:28: error: expected a qualified name after 'typename'
_LIBCPP_CONSTEXPR typename enable_if<is_floating_point<_A1>::value, bool>::type
                           ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:552:37: error: expected ';' at end of declaration
_LIBCPP_CONSTEXPR typename enable_if<is_floating_point<_A1>::value, bool>::type
                                    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:552:37: error: expected unqualified-id
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:564:39: error: use of undeclared identifier 'is_floating_point'
_LIBCPP_CONSTEXPR typename enable_if<!is_floating_point<_A1>::value, bool>::type
                                      ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:564:57: error: '_A1' does not refer to a value
_LIBCPP_CONSTEXPR typename enable_if<!is_floating_point<_A1>::value, bool>::type
                                                        ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:562:17: note: declared here
template <class _A1>
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Diag.o] Error 1
ERROR: compilation failed for package ‘Rfast’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rfast’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rfast’

The downloaded source packages are in
	‘/private/var/folders/_3/_hmmdm0d3b94hb2s2r7t37c00000gn/T/RtmpSCyQ1m/downloaded_packages’
Warning messages:
1: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘deldir’ had non-zero exit status
2: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘Rfast’ had non-zero exit status

**Comment by drisso** [comment]
Hi @lizhaozhi,

sorry that I missed this. Have you solved this issue or do you still need help? 

In any case, it seems that the error message is quite clear:
```
ERROR: compilation failed for package ‘Rfast’
```

You need to investigate why the `Rfast` package is failling to install and continue from there.
