### ISSUE TITLE
How to decide the the number of factors of unwanted variation to be estimated from the data.

### ISSUE THREAD

**Issue by lizhaozhi** [drisso/RUVSeq#5]
HI,
I am new to RUV. I want to know is there any way to decide the number of factors of unwanted variation to be estimated from the data.  I am using RUVr().

Thank you

**Comment by drisso** [comment]
Hi @lizhaozhi,

there is no "rule" set in stone for selecting the number of factors. We suggest to perform extensive exploratory data analysis, e.g., by looking at RLE plots and at the distribution of the first two-three principal components after the correction to see whether the unwanted variation has been adjusted for. 

We discuss this in a bit more details in our paper (see "Choice of number of factors of unwanted variation" paragraph):
https://www.nature.com/articles/nbt.2931

Finally, please note that github issues should be about technical aspects of the package, for general queries about its use, in the future please consider the Bioconductor support forum: support.bioconductor.org
