### ISSUE TITLE
How to get the ERCCs-adjusted CPM value after RUVg

### ISSUE THREAD

**Issue by zhouqz** [drisso/RUVSeq#6]
Dear All,

Which way is the best to get the ERCCs-adjusted CPM value after RUVg.

I see someone use the normalizedCounts to calculate the CPM.

ruvg <- RUVg(counts(umi.qc), erccs, k = 1)
assay(umi.qc, "ruvg1") <- log2(
    t(t(ruvg$normalizedCounts) / colSums(ruvg$normalizedCounts) * 1e6) + 1
)

The normalizedCounts can be compared directly across the samples, so this way seems no make sense.

Thanks & Best,
Zhou

**Comment by drisso** [comment]
Hi Zhou,

first of all, thanks for your interest in RUVSeq. This is an interesting question, but it's not related to issues with the software, rather with its use. Hence, the appropriate channel for this question is [the Bioconductor support forum](https://support.bioconductor.org/), in which other experts can weigh in with their thoughts.

I'm not sure what you mean by "adjusted CPM" values. CPM is a kind of normalization. Obviously, the `normalizedCounts` in the RUV output will contain data normalized with a different method. I don't think it makes much sense to CPM-normalize the already normalized data. 

What exactly are you trying to achieve with your code?

Please, let's continue this conversation on the support forum.

**Comment by zhouqz** [comment]
Hi Davide,

Yes, CPM is a kind of normalization. But like the edgeR, the final CPM was
adjusted by the TMM factor. Here, I want to get the CPM containing the
normalization with ERCCs. So I can use the CPM value to do the comparison
between samples.

Thanks & Best,
Qiuzhong

**Comment by drisso** [comment]
I assume you're talking about edgeR's `cpm()` function, which uses TMM factors to "adjust" the total count in the CPM normalization. You can do the same with any global scaling normalization, but not with RUV's adjusted counts as this is not a global scaling. 

I'm not sure why you are set on using CPM values, I would simply use the normalizedCounts from RUVSeq in place of CPM.

**Comment by drisso** [comment]
Unfortunately, as I said in my previous comment, it is not currently possible to obtain "RUV's adjusted CPM".

Best,
Davide

**Comment by zhouqz** [comment]
Dear Davide,

Thank you so much again for your assistance.

Thanks & Best,
Qiuzhong
