### ISSUE TITLE
Need guidance for uneven samples

### ISSUE THREAD

**Issue by devenderarora** [drisso/RUVSeq#8]
Respected Developer,
I have used your superb amazing R package for batch effect analysis but for one data I am having issue in defining number of samples.
As the below script
x <- as.factor(rep(c("Ctl", "Trt"), each=3))
which explain we have 3 samples each but in my case we have ctrl 4 and trt 5 samples. Can you share how to handle such uneven data to serve the purpose. I am having issue and couldn't find  any resolution yet. 

Thankyou

**Comment by drisso** [comment]
Hi @devenderarora,

first of all, thanks for your interest in RUVSeq. If I understand correctly, what you are asking is a basic R question, namely how to define a factor with two levels with 4 and 5 elements. (If I misunderstood the question, please let me know).

This can be achieved in a number of ways, e.g.

```{r}
x <- as.factor(c(rep("Ctl", 4), rep("Trt", 5)))
```

This of course assumes that the columns of your data matrix are ordered by treatment (with controls first and then treated).

I didn't mind helping you with this question but note that it is a basic R question. This forum is supposed to be about bugs or other issues with the RUVSeq package. There are many great (and free!) resources to learn R that could be useful for this type of questions (e.g., the [software carpentry](https://software-carpentry.org/) or the [bioconductor courses](http://bioconductor.org/help/course-materials/)). And if you still have questions on the _use_ of Bioconductor packages (such as RUVSeq or others), you can ask the [support forum](https://support.bioconductor.org/), in which other experts can weigh in with their thoughts.

Best,
Davide
